[package]
name = "dadjoke"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
axum = { version = "0.7.4" }
tokio = { version = "1.36.0", features = ["full"] }
